# Generated by Django 2.2.6 on 2019-10-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLVL',
            fields=[
                ('lvl', models.IntegerField(default='1', primary_key=True, serialize=False)),
                ('lvlxp', models.IntegerField(default='120')),
            ],
        ),
    ]
