# Generated by Django 2.2.6 on 2019-10-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlvl',
            name='lvlreward',
            field=models.IntegerField(default='1'),
        ),
    ]
