# Generated by Django 2.2.6 on 2019-10-20 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleXp',
            fields=[
                ('user_buff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('buff', models.IntegerField(default='1', editable=False)),
                ('buffName', models.CharField(default='Эссенция двойного опыта', max_length=150)),
                ('buffInfo', models.CharField(default='Удваивает опыт на 15 боёв', max_length=150)),
                ('buffimg', models.ImageField(upload_to='Buffimg')),
                ('buffCount', models.IntegerField(default='15')),
                ('priceGold', models.IntegerField(default='500')),
                ('priceKnights', models.IntegerField(default='2')),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
