# Generated by Django 2.2.6 on 2019-10-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublexp',
            name='buffimg',
        ),
    ]
