# Generated by Django 2.2.6 on 2019-10-20 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('bonus', '0002_remove_doublexp_buffimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleGold',
            fields=[
                ('user_buff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('buff', models.IntegerField(default='2', editable=False)),
                ('priceKnights', models.IntegerField(default='4')),
                ('accept_time', models.DateTimeField(default=None)),
                ('exp_time', models.DateTimeField(default=None)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='doublexp',
            name='buffInfo',
        ),
        migrations.RemoveField(
            model_name='doublexp',
            name='buffName',
        ),
    ]
