# Generated by Django 2.2.6 on 2019-10-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_auto_20191020_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublexp',
            name='Get_link',
            field=models.CharField(default='goldBonus', max_length=50),
        ),
    ]
