# Generated by Django 2.2.6 on 2019-10-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0004_doublexp_get_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublexp',
            name='Get_link',
        ),
        migrations.AddField(
            model_name='doublegold',
            name='Get_link',
            field=models.CharField(default='goldBonus', max_length=50),
        ),
    ]
