# Generated by Django 2.2.6 on 2019-10-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0005_auto_20191027_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublexp',
            name='Get_xp',
            field=models.CharField(default='XpBonus', max_length=50),
        ),
    ]
