# Generated by Django 2.2.6 on 2019-10-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0006_doublexp_get_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublexp',
            name='priceGold',
        ),
    ]
