# Generated by Django 2.2.6 on 2019-10-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WinRowTast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(default='Первая кровь', max_length=64)),
                ('taskInfo', models.CharField(default='Проведи 5 боев', max_length=160)),
                ('taskReward_sc', models.IntegerField(default=750)),
                ('taskReward_knights', models.IntegerField(default=5)),
                ('taskReward_xp', models.IntegerField(default=40)),
                ('taskWinCount', models.IntegerField(default=5)),
                ('taskImg', models.ImageField(upload_to='taskImg')),
            ],
        ),
    ]
