# Generated by Django 2.2.6 on 2019-10-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WinRowTast',
            new_name='WinRowTask',
        ),
    ]
