# Generated by Django 2.2.6 on 2019-10-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvest', '0002_auto_20191027_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='winrowtask',
            name='taskLevel',
            field=models.IntegerField(default=1),
        ),
    ]
