# Generated by Django 2.2.6 on 2019-10-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvest', '0004_auto_20191027_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='winrowtask',
            name='taskStatus',
            field=models.BooleanField(default=False),
        ),
    ]
