# Generated by Django 2.2.6 on 2019-10-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvest', '0005_winrowtask_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='upherostat',
            name='TaskDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='winrowtask',
            name='taskCurrentWin',
            field=models.IntegerField(default=0),
        ),
    ]
