# Generated by Django 2.2.6 on 2019-10-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('silver_coin', models.IntegerField(default='1000')),
                ('knights', models.IntegerField(default='75')),
                ('power', models.IntegerField(default='85')),
                ('level', models.IntegerField(default='1')),
                ('xp', models.IntegerField(default='0')),
                ('energy', models.IntegerField(default=100)),
                ('totalWin', models.IntegerField(default=0)),
                ('isComplete', models.BooleanField(default=False)),
            ],
        ),
    ]
