# Generated by Django 2.2.6 on 2019-10-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='rudnik_level',
            field=models.IntegerField(default=1),
        ),
    ]
