# Generated by Django 2.2.6 on 2019-10-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uinfo', '0002_userattribute_rudnik_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='last_accept_rudnik',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='userattribute',
            name='now_accept_rudnik',
            field=models.DateField(default=None),
        ),
    ]
