# Generated by Django 2.2.6 on 2019-10-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uinfo', '0003_auto_20191026_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattribute',
            name='now_accept_rudnik',
        ),
    ]
