# Generated by Django 2.2.6 on 2019-10-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uinfo', '0004_remove_userattribute_now_accept_rudnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='energy_time',
            field=models.DateTimeField(default=None),
        ),
    ]
