# Generated by Django 2.2.6 on 2019-10-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uinfo', '0005_userattribute_energy_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='energy_max',
            field=models.IntegerField(default=100),
        ),
    ]
