# Generated by Django 2.2.6 on 2019-10-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rudnik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rudnikmodel',
            name='last_accept',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='rudnikmodel',
            name='now_accept',
            field=models.DateField(default=None),
        ),
    ]
