# Generated by Django 2.2.6 on 2019-10-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rudnik', '0002_auto_20191026_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rudnikmodel',
            name='last_accept',
        ),
        migrations.RemoveField(
            model_name='rudnikmodel',
            name='now_accept',
        ),
    ]
