# Generated by Django 2.2.6 on 2019-10-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rudnik', '0003_auto_20191026_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertKnights',
            fields=[
                ('SilverCount', models.IntegerField(default=30000, primary_key=True, serialize=False)),
                ('KnightsPrice', models.IntegerField(default=5)),
            ],
        ),
    ]
