# Generated by Django 2.2.6 on 2019-10-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='up_armour',
            fields=[
                ('armour_level', models.IntegerField(primary_key=True, serialize=False)),
                ('armour', models.IntegerField(default=12)),
                ('price_sc', models.IntegerField(default=450)),
                ('price_knights', models.IntegerField(default=3)),
                ('url', models.CharField(default='link', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='up_hp',
            fields=[
                ('hp_level', models.IntegerField(primary_key=True, serialize=False)),
                ('hp', models.IntegerField(default=12)),
                ('price_sc', models.IntegerField(default=450)),
                ('price_knights', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='up_pwr',
            fields=[
                ('pwr_level', models.IntegerField(primary_key=True, serialize=False)),
                ('pwr', models.IntegerField(default=12)),
                ('price_sc', models.IntegerField(default=450)),
                ('price_knights', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeroName', models.CharField(default='Лорд Крестоносец', max_length=32)),
                ('attackPower', models.IntegerField(default='25')),
                ('armour', models.IntegerField(default='25')),
                ('hitPoint', models.IntegerField(default='85')),
                ('imghero', models.ImageField(upload_to='heroimage')),
                ('herolevel', models.IntegerField(default='1')),
                ('IsActive', models.BooleanField(default=False)),
                ('win', models.IntegerField(default='0')),
                ('pwr_level', models.IntegerField(default=1)),
                ('armour_level', models.IntegerField(default=1)),
                ('hp_level', models.IntegerField(default=1)),
                ('heroid', models.IntegerField(default=1)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
