# Generated by Django 2.2.6 on 2019-10-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='up_hp',
            name='link_hp',
            field=models.IntegerField(default=20),
        ),
    ]
