# Generated by Django 2.2.6 on 2019-10-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhero', '0002_up_hp_link_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up_hp',
            name='link_hp',
            field=models.CharField(default='link', max_length=50),
        ),
    ]
