# Generated by Django 2.2.6 on 2019-10-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeroName', models.CharField(default='Лорд Крестоносец', max_length=32)),
                ('HeroPower', models.IntegerField(default='25')),
                ('HeroArmour', models.IntegerField(default='25')),
                ('HeroHp', models.IntegerField(default='85')),
                ('HeroImg', models.ImageField(upload_to='Hero_image')),
                ('HeroLevel', models.IntegerField(default='1')),
                ('price_silver_coin', models.IntegerField(default='500')),
                ('priceKnights', models.IntegerField(default='25')),
            ],
        ),
    ]
